# -*- coding: utf-8 -*-
"""train_models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weMn11s1VrQ3R6ajf3c5w7OXPD6PkIvU
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    matthews_corrcoef
)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier


def train_all_models(df):
    # -------------------------------
    # Encode categorical variables
    # -------------------------------
    df_encoded = df.copy()
    for col in df_encoded.select_dtypes(include="object").columns:
        le = LabelEncoder()
        df_encoded[col] = le.fit_transform(df_encoded[col])

    X = df_encoded.drop("HeartDisease", axis=1)
    y = df_encoded["HeartDisease"]

    # -------------------------------
    # Train-test split
    # -------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # -------------------------------
    # Models
    # -------------------------------
    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Decision Tree": DecisionTreeClassifier(random_state=42),
        "KNN": KNeighborsClassifier(),
        "Naive Bayes": GaussianNB(),
        "Random Forest": RandomForestClassifier(random_state=42),
        "XGBoost": XGBClassifier(
            eval_metric="logloss",
            random_state=42,
            use_label_encoder=False
        )
    }

    results = {}
    predictions = {}

    # -------------------------------
    # Train & evaluate
    # -------------------------------
    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        # AUC Score
        if hasattr(model, "predict_proba"):
            y_prob = model.predict_proba(X_test)[:, 1]
            auc = roc_auc_score(y_test, y_prob)
        else:
            auc = roc_auc_score(y_test, y_pred)

        mcc = matthews_corrcoef(y_test, y_pred)

        results[name] = {
            "accuracy": round(accuracy_score(y_test, y_pred), 4),
            "auc": round(auc, 4),
            "precision": round(precision_score(y_test, y_pred), 4),
            "recall": round(recall_score(y_test, y_pred), 4),
            "f1_score": round(f1_score(y_test, y_pred), 4),
            "mcc": round(mcc, 4)
        }

        predictions[name] = {
            "y_test": y_test,
            "y_pred": y_pred
        }

    return results, predictions