# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kRzwk8nHywA2W1_DPTSpcrYs0VZJBdd
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from model.train_models import train_all_models

# ---------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------
st.set_page_config(
    page_title="ML Assignment 2 - Classification Models",
    layout="wide"
)

st.title("Machine Learning Classification Models Comparison")
st.write(
    "This application compares multiple machine learning classification models "
    "using standard evaluation metrics."
)

# ---------------------------------------------------
# FILE UPLOADER
# ---------------------------------------------------
uploaded_file = st.file_uploader(
    "Upload Heart Disease CSV file",
    type=["csv"]
)

# ---------------------------------------------------
# MAIN LOGIC
# ---------------------------------------------------
if uploaded_file is not None:
    try:
        df = pd.read_csv(uploaded_file)

        st.success("✅ Dataset loaded successfully")

        st.subheader("Dataset Preview")
        st.dataframe(df.head())

        if "HeartDisease" not in df.columns:
            st.error("❌ Target column 'HeartDisease' not found in dataset.")
        else:
            with st.spinner("Training models and evaluating metrics..."):
                out = train_all_models(df)
                results = out[0]
                predictions = out[1]

            # -------------------------------
            # Metrics Table
            # -------------------------------
            metrics_df = pd.DataFrame(results).T
            st.subheader("Model Evaluation Metrics")
            st.dataframe(metrics_df)

            # Best model
            best_model = metrics_df["accuracy"].idxmax()
            st.success(f"🏆 Best Model (Accuracy): {best_model}")

            # -------------------------------
            # Model Selection
            # -------------------------------
            model_choice = st.selectbox(
                "Select a model",
                metrics_df.index
            )

            st.subheader(f"Metrics for {model_choice}")
            st.json(results[model_choice])

            # -------------------------------
            # Confusion Matrix
            # -------------------------------
            st.subheader("Confusion Matrix")

            y_test = predictions[model_choice]["y_test"]
            y_pred = predictions[model_choice]["y_pred"]

            cm = confusion_matrix(y_test, y_pred)

            fig, ax = plt.subplots(figsize=(4, 3))
            sns.heatmap(
                cm,
                annot=True,
                fmt="d",
                cmap="Blues",
                ax=ax
            )
            ax.set_xlabel("Predicted")
            ax.set_ylabel("Actual")
            ax.set_title(f"Confusion Matrix - {model_choice}")

            st.pyplot(fig)

    except Exception as e:
        st.error("❌ An error occurred while processing the file.")
        st.exception(e)

else:
    st.info("📂 Please upload a CSV file to begin.")